// samples/form-filler/src/IncidentForm.tsx
import React, { forwardRef, useImperativeHandle, useState, useCallback } from 'react';

export interface IncidentFormData {
  fullName: string;
  email: string;
  incidentType: string;
  dateOfIncident: string;
  impactLevel: string;
  description: string;
  suggestedActions: string;
}

export interface IncidentFormRef {
  setValue: (field: keyof IncidentFormData, value: string) => void;
  getValues: () => IncidentFormData;
  reset: () => void;
  submit: () => Promise<{ success: boolean; message: string }>;
  getFieldOptions: (field: string) => string[] | null;
}

const defaultValues: IncidentFormData = {
  fullName: '',
  email: '',
  incidentType: '',
  dateOfIncident: '',
  impactLevel: '',
  description: '',
  suggestedActions: '',
};

const incidentTypeOptions = [
  'Data Breach',
  'Unauthorized Access',
  'Malware',
  'Phishing',
  'Other',
];

const impactLevelOptions = ['Low', 'Medium', 'High', 'Critical'];

const IncidentForm = forwardRef<IncidentFormRef>((_, ref) => {
  const [formData, setFormData] = useState<IncidentFormData>(defaultValues);
  const [submitStatus, setSubmitStatus] = useState<'idle' | 'success' | 'error'>('idle');

  const setValue = useCallback((field: keyof IncidentFormData, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    setSubmitStatus('idle');
  }, []);

  const getValues = useCallback(() => formData, [formData]);

  const reset = useCallback(() => {
    setFormData(defaultValues);
    setSubmitStatus('idle');
  }, []);

  const submit = useCallback(async (): Promise<{ success: boolean; message: string }> => {
    const required: (keyof IncidentFormData)[] = ['fullName', 'email', 'incidentType', 'dateOfIncident', 'impactLevel', 'description'];
    const missing = required.filter((field) => !formData[field]);

    if (missing.length > 0) {
      setSubmitStatus('error');
      return {
        success: false,
        message: `Missing required fields: ${missing.join(', ')}`,
      };
    }

    setSubmitStatus('success');
    return {
      success: true,
      message: 'Security incident report submitted successfully!',
    };
  }, [formData]);

  const getFieldOptions = useCallback((field: string): string[] | null => {
    if (field === 'incidentType') return incidentTypeOptions;
    if (field === 'impactLevel') return impactLevelOptions;
    return null;
  }, []);

  useImperativeHandle(ref, () => ({
    setValue,
    getValues,
    reset,
    submit,
    getFieldOptions,
  }), [setValue, getValues, reset, submit, getFieldOptions]);

  const handleChange = (field: keyof IncidentFormData) => (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>
  ) => {
    setValue(field, e.target.value);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await submit();
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <div style={styles.header}>
          <h2 style={styles.title}>Security Incident Report</h2>
          <p style={styles.subtitle}>Please fill out the form below to report an incident</p>
        </div>

        <form onSubmit={handleSubmit} style={styles.form}>
          <div style={styles.fieldGroup}>
            <label style={styles.label}>Full Name</label>
            <input
              type="text"
              value={formData.fullName}
              onChange={handleChange('fullName')}
              placeholder="Enter your full name"
              style={styles.input}
            />
          </div>

          <div style={styles.fieldGroup}>
            <label style={styles.label}>Email</label>
            <input
              type="email"
              value={formData.email}
              onChange={handleChange('email')}
              placeholder="your.email@company.com"
              style={styles.input}
            />
          </div>

          <div style={styles.row}>
            <div style={styles.fieldGroupHalf}>
              <label style={styles.label}>Incident Type</label>
              <select
                value={formData.incidentType}
                onChange={handleChange('incidentType')}
                style={styles.select}
              >
                <option value="">Select type...</option>
                {incidentTypeOptions.map((opt) => (
                  <option key={opt} value={opt}>{opt}</option>
                ))}
              </select>
            </div>

            <div style={styles.fieldGroupHalf}>
              <label style={styles.label}>Date of Incident</label>
              <input
                type="date"
                value={formData.dateOfIncident}
                onChange={handleChange('dateOfIncident')}
                style={styles.input}
              />
            </div>
          </div>

          <div style={styles.fieldGroup}>
            <label style={styles.label}>Impact Level</label>
            <select
              value={formData.impactLevel}
              onChange={handleChange('impactLevel')}
              style={styles.select}
            >
              <option value="">Select impact level...</option>
              {impactLevelOptions.map((opt) => (
                <option key={opt} value={opt}>{opt}</option>
              ))}
            </select>
          </div>

          <div style={styles.fieldGroup}>
            <label style={styles.label}>Incident Description</label>
            <textarea
              value={formData.description}
              onChange={handleChange('description')}
              placeholder="Describe the incident in detail..."
              rows={4}
              style={styles.textarea}
            />
          </div>

          <div style={styles.fieldGroup}>
            <label style={styles.label}>Suggested Actions</label>
            <textarea
              value={formData.suggestedActions}
              onChange={handleChange('suggestedActions')}
              placeholder="Any recommended actions or remediation steps..."
              rows={3}
              style={styles.textarea}
            />
          </div>

          {submitStatus === 'success' && (
            <div style={styles.successMessage}>
              Report submitted successfully!
            </div>
          )}

          {submitStatus === 'error' && (
            <div style={styles.errorMessage}>
              Please fill in all required fields.
            </div>
          )}

          <button type="submit" style={styles.submitButton}>
            Submit Report
          </button>
        </form>
      </div>
    </div>
  );
});

IncidentForm.displayName = 'IncidentForm';

const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: '24px',
    height: '100%',
    overflow: 'auto',
    background: '#0f0f1a',
  },
  card: {
    width: '100%',
    maxWidth: '480px',
    background: '#ffffff',
    borderRadius: '12px',
    boxShadow: '0 4px 24px rgba(0, 0, 0, 0.3)',
    overflow: 'hidden',
  },
  header: {
    padding: '24px 24px 16px',
    borderBottom: '1px solid #e5e7eb',
  },
  title: {
    margin: 0,
    fontSize: '20px',
    fontWeight: 600,
    color: '#111827',
  },
  subtitle: {
    margin: '6px 0 0',
    fontSize: '14px',
    color: '#6b7280',
  },
  form: {
    padding: '20px 24px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  fieldGroupHalf: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  row: {
    display: 'flex',
    gap: '12px',
  },
  label: {
    fontSize: '13px',
    fontWeight: 500,
    color: '#374151',
  },
  input: {
    padding: '10px 12px',
    fontSize: '14px',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    outline: 'none',
    transition: 'border-color 0.15s, box-shadow 0.15s',
    background: '#fff',
    color: '#111827',
  },
  select: {
    padding: '10px 12px',
    fontSize: '14px',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    outline: 'none',
    background: '#fff',
    color: '#111827',
    cursor: 'pointer',
  },
  textarea: {
    padding: '10px 12px',
    fontSize: '14px',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    outline: 'none',
    resize: 'vertical',
    fontFamily: 'inherit',
    background: '#fff',
    color: '#111827',
  },
  submitButton: {
    marginTop: '8px',
    padding: '12px 20px',
    fontSize: '14px',
    fontWeight: 600,
    color: '#fff',
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'transform 0.15s, box-shadow 0.15s',
  },
  successMessage: {
    padding: '12px 16px',
    background: '#d1fae5',
    color: '#065f46',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 500,
  },
  errorMessage: {
    padding: '12px 16px',
    background: '#fee2e2',
    color: '#991b1b',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 500,
  },
};

export default IncidentForm;

// samples/form-filler-angular/src/app/incident-form.component.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

export interface IncidentFormData {
  fullName: string;
  email: string;
  incidentType: string;
  dateOfIncident: string;
  impactLevel: string;
  description: string;
  suggestedActions: string;
}

const defaultValues: IncidentFormData = {
  fullName: '',
  email: '',
  incidentType: '',
  dateOfIncident: '',
  impactLevel: '',
  description: '',
  suggestedActions: '',
};

const incidentTypeOptions = ['Data Breach', 'Unauthorized Access', 'Malware', 'Phishing', 'Other'];
const impactLevelOptions = ['Low', 'Medium', 'High', 'Critical'];

/**
 * Angular port of the React sample's IncidentForm. Angular has no
 * `useImperativeHandle` equivalent, so the parent gets at this component's
 * `setValue`/`getValues`/`reset`/`submit`/`getFieldOptions` API the native
 * way: via `@ViewChild(IncidentFormComponent)`.
 */
@Component({
  selector: 'app-incident-form',
  standalone: true,
  imports: [FormsModule],
  changeDetection: ChangeDetectionStrategy.Default,
  template: `
    <div class="container">
      <div class="card">
        <div class="header">
          <h2 class="title">Security Incident Report</h2>
          <p class="subtitle">Please fill out the form below to report an incident</p>
        </div>

        <form class="form" (submit)="onSubmit($event)">
          <div class="field-group">
            <label class="label">Full Name</label>
            <input class="input" type="text" [(ngModel)]="data.fullName" name="fullName" placeholder="Enter your full name" (ngModelChange)="onDirty()" />
          </div>

          <div class="field-group">
            <label class="label">Email</label>
            <input class="input" type="email" [(ngModel)]="data.email" name="email" placeholder="your.email@company.com" (ngModelChange)="onDirty()" />
          </div>

          <div class="row">
            <div class="field-group-half">
              <label class="label">Incident Type</label>
              <select class="select" [(ngModel)]="data.incidentType" name="incidentType" (ngModelChange)="onDirty()">
                <option value="">Select type...</option>
                @for (opt of incidentTypeOptions; track opt) {
                  <option [value]="opt">{{ opt }}</option>
                }
              </select>
            </div>
            <div class="field-group-half">
              <label class="label">Date of Incident</label>
              <input class="input" type="date" [(ngModel)]="data.dateOfIncident" name="dateOfIncident" (ngModelChange)="onDirty()" />
            </div>
          </div>

          <div class="field-group">
            <label class="label">Impact Level</label>
            <select class="select" [(ngModel)]="data.impactLevel" name="impactLevel" (ngModelChange)="onDirty()">
              <option value="">Select impact level...</option>
              @for (opt of impactLevelOptions; track opt) {
                <option [value]="opt">{{ opt }}</option>
              }
            </select>
          </div>

          <div class="field-group">
            <label class="label">Incident Description</label>
            <textarea class="textarea" rows="4" [(ngModel)]="data.description" name="description" placeholder="Describe the incident in detail..." (ngModelChange)="onDirty()"></textarea>
          </div>

          <div class="field-group">
            <label class="label">Suggested Actions</label>
            <textarea class="textarea" rows="3" [(ngModel)]="data.suggestedActions" name="suggestedActions" placeholder="Any recommended actions or remediation steps..." (ngModelChange)="onDirty()"></textarea>
          </div>

          @if (submitStatus() === 'success') {
            <div class="success-message">Report submitted successfully!</div>
          }
          @if (submitStatus() === 'error') {
            <div class="error-message">Please fill in all required fields.</div>
          }

          <button type="submit" class="submit-button">Submit Report</button>
        </form>
      </div>
    </div>
  `,
  styles: [`
    .container { display: flex; align-items: flex-start; justify-content: center; padding: 24px; height: 100%; overflow: auto; background: #0f0f1a; box-sizing: border-box; }
    .card { width: 100%; max-width: 480px; background: #fff; border-radius: 12px; box-shadow: 0 4px 24px rgba(0,0,0,0.3); overflow: hidden; }
    .header { padding: 24px 24px 16px; border-bottom: 1px solid #e5e7eb; }
    .title { margin: 0; font-size: 20px; font-weight: 600; color: #111827; }
    .subtitle { margin: 6px 0 0; font-size: 14px; color: #6b7280; }
    .form { padding: 20px 24px 24px; display: flex; flex-direction: column; gap: 16px; }
    .field-group { display: flex; flex-direction: column; gap: 6px; }
    .field-group-half { flex: 1; display: flex; flex-direction: column; gap: 6px; }
    .row { display: flex; gap: 12px; }
    .label { font-size: 13px; font-weight: 500; color: #374151; }
    .input, .select, .textarea { padding: 10px 12px; font-size: 14px; border: 1px solid #d1d5db; border-radius: 8px; outline: none; background: #fff; color: #111827; font-family: inherit; }
    .textarea { resize: vertical; }
    .select { cursor: pointer; }
    .submit-button { margin-top: 8px; padding: 12px 20px; font-size: 14px; font-weight: 600; color: #fff; background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); border: none; border-radius: 8px; cursor: pointer; }
    .success-message { padding: 12px 16px; background: #d1fae5; color: #065f46; border-radius: 8px; font-size: 14px; font-weight: 500; }
    .error-message { padding: 12px 16px; background: #fee2e2; color: #991b1b; border-radius: 8px; font-size: 14px; font-weight: 500; }
  `],
})
export class IncidentFormComponent {
  data: IncidentFormData = { ...defaultValues };
  submitStatus = signal<'idle' | 'success' | 'error'>('idle');

  readonly incidentTypeOptions = incidentTypeOptions;
  readonly impactLevelOptions = impactLevelOptions;

  onDirty(): void {
    this.submitStatus.set('idle');
  }

  setValue(field: keyof IncidentFormData, value: string): void {
    this.data = { ...this.data, [field]: value };
    this.submitStatus.set('idle');
  }

  getValues(): IncidentFormData {
    return this.data;
  }

  reset(): void {
    this.data = { ...defaultValues };
    this.submitStatus.set('idle');
  }

  async submit(): Promise<{ success: boolean; message: string }> {
    const required: (keyof IncidentFormData)[] = ['fullName', 'email', 'incidentType', 'dateOfIncident', 'impactLevel', 'description'];
    const missing = required.filter((field) => !this.data[field]);

    if (missing.length > 0) {
      this.submitStatus.set('error');
      return { success: false, message: `Missing required fields: ${missing.join(', ')}` };
    }

    this.submitStatus.set('success');
    return { success: true, message: 'Security incident report submitted successfully!' };
  }

  getFieldOptions(field: string): string[] | null {
    if (field === 'incidentType') return incidentTypeOptions;
    if (field === 'impactLevel') return impactLevelOptions;
    return null;
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    void this.submit();
  }
}
